apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-deployment
spec:
  selector:
    matchLabels:
      app: health-check
  template:
    metadata:
      labels:
        app: health-check
    spec:
      containers:
        - name: health-check-container
          image: telegram_sender:latest
          # Other container specifications
